### ISSUE TITLE
Gridbox Connector startet nicht mehr

### ISSUE THREAD

**Issue by msommerx** [unl0ck/viessmann-gridbox-connector#6]
(Vermutlich) seit dem Home Assistant Update bekomme ich eine Fehlermeldung wenn ich das Plugin starte.

[16:49:24] INFO: Starting GridboxConnector...
s6-rc: info: service legacy-services successfully started
[16:49:24] ERROR: Got unexpected response from the API: Service not enabled
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K Aug 11 16:49 .
     4 drwxr-xr-x    1 root     root        4.0K Aug 11 16:49 ..
     4 -rw-------    1 root     root         187 Aug 11 16:49 options.json
total 16K    
     4 drwxr-xr-x    1 root     root        4.0K Jul 22 09:45 .
     4 drwxr-xr-x    1 root     root        4.0K Aug 11 16:49 ..
     4 drwxr-xr-x    3 root     root        4.0K Jul 22 09:45 GridboxConnector
     4 -rw-r--r--    1 root     root         494 Jul 22 09:45 cloudSettings.json
/build
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 71, in <module>
    run_addon()
  File "/build/GridboxConnector/__main__.py", line 47, in run_addon
    logger.error("MQTT settings not set")
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1633, in handle
    if (not self.disabled) and self.filter(record):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 821, in filter
    result = f.filter(record)
  File "/build/GridboxConnector/utils.py", line 8, in filter
    literal_msg = ast.literal_eval(message)
  File "/usr/local/lib/python3.10/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/usr/local/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    MQTT settings not set
         ^^^^^^^^
SyntaxError: invalid syntax
[16:49:25] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Ich wäre für einen Hinweis dankbar!
Viele Grüße!

**Comment by unl0ck** [comment]
Dir fehlt MQTT steht da das das nicht gesetzt ist

**Comment by msommerx** [comment]
Ich habe es gerade noch mal neu installiert und auch den MQTT neu eingetragen. In der Konfiguration war vor der Neuinstallation allerdings alles eingetragen. 
Jetzt läuft es wieder. Sehr komisch... 
Danke!
